development:
  adapter: postgresql
  encoding: unicode
  database: air_quality_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: air_quality_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: air_quality_production
  pool: 5
  username:
  password:
